### ISSUE TITLE
differentiable vdW softcores

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#106]
This too, will be fun

**Comment by jchodera** [comment]
There are a few softcore models to consider:
* The original [Buetler softcore form](https://www.sciencedirect.com/science/article/abs/pii/0009261494003971?via%3Dihub)
* Generalized form from [Michael Shirts](https://aip.scitation.org/doi/abs/10.1063/1.3607597)
* This [linear version](https://www.mpibpc.mpg.de/277406/Buelens_2011_JCC_33_25-33.pdf) from Helmut Grubmüller
* An exciting improvement from [Bert de Groot](https://pubs.acs.org/doi/abs/10.1021/ct300220p)

**Comment by jchodera** [comment]
Though I'd question whether you really need this if the goal is to optimize to real physical measurements. You'd only want this capability if you want to optimize alchemical pathways for efficiency using advanced methods that [minimize thermodynamic length](http://threeplusone.com/gec/news/gingrich2016).

**Comment by jchodera** [comment]
You *will* want to support LJPME or long-range dispersion corrections for standard LJ models, though!

**Comment by proteneer** [comment]
Not needed right now.
