### ISSUE TITLE
GPU powered neighborlists

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#116]
It's starting to become pretty obvious that we're going to need to implement a neighborlist routine on the GPU. I'm implementing the coarse-grained Nblist + periodic hilbert sorting that we do in OpenMM.

**Comment by jchodera** [comment]
This would be in JAX, or a custom GPU kernel Op?

**Comment by proteneer** [comment]
custom GPU kernel - it's going to be a port of find interacting blocks initially. I'm still scoping out the work needed

**Comment by jchodera** [comment]
Might be interesting to rope in @peastman, since we're talking about writing custom Ops for ML plugins that do simpler things. Could be that the code could be shared.

**Comment by proteneer** [comment]
Being implemented in a separate branch. Will be submitted soon.
