### ISSUE TITLE
Issue Building  "contains a 128-bit integer, which is not supported in device code"

### ISSUE THREAD

**Issue by mikemhenry** [proteneer/timemachine#1257]
I tried to build time machine from source and I end up getting a lot of errors like this: 

`timemachine/cpp/src/fixed_point.hpp(24): error: "RealType (__int128_t)" contains a 128-bit integer, which is not supported in device code`

I am not sure if this is an issue with the card (GeForce RTX 2060) the compute capability (7.5), the CUDA version (12.3), gxx version (10.4.0) or the cuda compiler version (11.2.67). 

I am going to try building somewhere else (HPC with fancy GPUs), I suspect some lower end consumer cards can't handle 128 bit ints? Is this a known issue?

Thanks!

**Comment by proteneer** [comment]
CUDA compiler needs to be 11.5 or later

**Comment by mikemhenry** [comment]
Yep! I just had found this https://developer.nvidia.com/blog/implementing-high-precision-decimal-arithmetic-with-cuda-int128/

I was able to build it after I updated the compiler, thanks!
