### ISSUE TITLE
Do double precision accumulation of second order derivatives

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#127]
We should be sure to accumulate the adjoint derivatives in double precision. Note that we don't need to do these in fixed point because we don't care about determinism in the derivatives, only in the trajectory. Currently our errors for the tangent space derivatives have a relative error of 1e-4 compared to the double precision implementation. This is far, far too big.

**Comment by proteneer** [comment]
In fact, we should just switch everything (including coordinates) to always be double precision. There's relatively little overhead in doing integration itself with doubles.

**Comment by bp-kelley** [comment]
What will the error drop do?  1e-4 is pretty big even for single precision

**Comment by proteneer** [comment]
I'm not sure yet - basically all the instances where we're doing atomicAdds need to have a double precision accumulator.

**Comment by proteneer** [comment]
I've spent about 6 hours on this today - I've managed to get the forces to be within reasonable error but the hessian vector products are still failing

**Comment by proteneer** [comment]
Isolated the bug to the exclusion list - but I've spent way too long trying to figure this out so I will resume on Monday

**Comment by proteneer** [comment]
Fixed the bug in the exclusion list - it differed slightly from how the non-excluded implementation worked.

List of changes that need to be revered:

fast/water tests set E to 0
charge params set to 0 in system prep
fixed point need to b reset to 2^36

Will take care of this tomorrow

**Comment by proteneer** [comment]
single precision errors are down to 4e-6 for HvPs and 8e-7 for force accumulation on a large box of water!

**Comment by proteneer** [comment]
lj JvPs are failing d2U/dxdp is failing - possibly because we're mixing params types in the test?

**Comment by proteneer** [comment]
stabilized to around 2e-5 - this isn't great, but it's significantly better than where we were before.

**Comment by proteneer** [comment]
Implemented via #128
