### ISSUE TITLE
Enable automated testing

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#137]
We need to get the tests back-up. Going to dig around a little bit longer but I still haven't found a good GPU CI solution yet.

**Comment by ayushkarnawat** [comment]
## CircleCI
You probably already knew this, but CircleCI offers a GPU CI solution (at an unspecified custom price), which may be (currently) unfeasible for this project. Have you tried contacting them to inquire about free GPU CI testing for open source projects?

## GradientCI
Alternatively, [Gradient](https://gradient.paperspace.com), which also integrates with GitHub, recently launched a [free tier](https://gradient.paperspace.com/free-gpu) for their GPU testing that works on jupyter notebooks. Note that they have plans to extend this to full-scale GPU jobs (for the free tier) in the near future. The caveat is that notebooks will automatically shutdown after 6 hours per session and only 1 free notebook can be run at a time upto a max of 5 notebooks (see [pricing](https://gradient.paperspace.com/pricing)).

**Comment by proteneer** [comment]
We've moved this over to our own internal system. Thanks though.
