### ISSUE TITLE
inconsistent charge between protein force field and GBobc force field

### ISSUE THREAD

**Issue by chuantian** [proteneer/timemachine#149]
When we combine protein force field with GBobc force field, we need to be careful about charge consistency. We were planning to use GBobc2 (alpha/beta/gamma = 1.0/0.8/4.85) by loading amber10_obc.xml, but there's no corresponded protein force field (amber10.xml is not consistent with amber10_obc.xml) that have consistent charges. 
Right now, I identified several combinations in openMM xml file directory that can achieve consistency. The candidate combinations are:
hard-coded: GBobc1 (alpha/beta/gamma = 0.8/0.0/2.909125)
loaded: amber99sbildn.xml (or alternative torsion parameters: amber99.xml and amberfb15.xml)
loaded: amber99_obc.xml ( exactly same to amber96_obc.xml)

We can probably fix this later since it's not quite important right now.

**Comment by proteneer** [comment]
I think this has been fixed? @chuantian - okay to close?

**Comment by chuantian** [comment]
Yes!
