### ISSUE TITLE
Make PDB writing more robust.

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#174]
We need to make the PDB writing more robust:

1. Move the duplicated PDBWriter Class in parameterize_exp, parameterize_simple, and parameterize_batch into an external file.
2. Often times we end up writing very large coordinates before it hits the limit, we should detect this before hand. (eg. Use a distance filter in the write() method)
3. Catch the exception so it doesn't hang the subprocess.
4. Anything else you think would be useful!

@chuantian I'm giving this one to you

**Comment by chuantian** [comment]
No problem!

**Comment by proteneer** [comment]
Resolved by #175
