### ISSUE TITLE
Allow arbitrary cutoffs for nonbonded terms

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#193]
Right now nonbonded terms are set to 

```
if lamba_idx ==  0:
  w = 0
elif lamba_idx == 1:
  w = lambda
elif lambda_idx == -1:
  w = cutoff + lambda
```

So we need to interpolate from lambda=0 to lambda=cutoff, however the bonded lambdas are strictly between 0 and 1.

**Comment by proteneer** [comment]
I think we just need to modify this to:
```
if lamba_idx ==  0:
  w = 0
elif lamba_idx == 1:
  w = lambda*cutoff
elif lambda_idx == -1:
  w = cutoff + lambda*cutoff
```

**Comment by chuantian** [comment]
so that in the modification:
(0, c) and (c, 2c) work for all cutoff
instead of in the old:
(0, 1) and (1, 2) only when cutoff == 1

**Comment by proteneer** [comment]
This is implemented.
