### ISSUE TITLE
interpolation

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#196]
Suppose we're interested in computing a function U(x; p(lambda)), where p is linearly rescaled between two parameters:

p =  lambda*p_i + (1-lambda)*p_j

We can compute dU_lambda using:

dU/dlambda = dU/dp.dp/dlambda = dU/dp . (p_i - p_j)

Fortunately, we're already able to compute dU/dp, giving us an analytical form

**Comment by proteneer** [comment]
After chatting with @chuantian, we can use the old school approach of:

U(x, params, lambda) = lambda*U0(x,params) + (1-lambda)*U1(x,params)

**Comment by jchodera** [comment]
Note that, for some potentials, this can introduce intermediate barriers that may be undesirable for sampling.

**Comment by chuantian** [comment]
@jchodera which potential are you referring to specifically? or are you saying the assumption behind linearly scaling two potentials might not be adaptable to all potential formulas?

**Comment by proteneer** [comment]
After an extensive amount of discussion with various folks, I think the path forward is:

1. Linear mixing for all terms except GB
2. GB will be interpolated as it doesn't have exclusions, however, it requires computation of dU/dp in the inference phase, which may slow down inference some what. Backwards pass is roughly the same.

**Comment by proteneer** [comment]
The first part is resolved, will open another PR for the parameter interpolation later.
