### ISSUE TITLE
Improve multi-node performance

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#245]
When running on 128 gpus we need to improve the performance of the synchronization step - if each job takes 1 second it implies we will waste ~2 minutes on *just* the synchronization step itself per mini-batch. We can definitely make this much better.

**Comment by proteneer** [comment]
looks like i finally get to play with asyncio for this one!

**Comment by bp-kelley** [comment]
Does the gpu code release the Gil?

**Comment by proteneer** [comment]
The GPU code is ran entirely in a different process (and often times a different server), so the GIL release doesn't matter from the point of view of the trainer code. 

It also looks like asyncio  compatibility is currently in grpc.experimental - so I'm going to wait for another ~6 months or so until its stable. I've identified most of the bottlenecks and I think we will incur only at a minimal amount of overhead.

**Comment by proteneer** [comment]
done via #254
