### ISSUE TITLE
Installation troubleshooting

### ISSUE THREAD

**Issue by maxentile** [proteneer/timemachine#266]
Thank you for making this project open source. I look forward to contributing to this project in the near future.

Documenting here a few installation hiccups I've encountered, and some possible workarounds. If these workarounds sound okay, I intend to open a small PR in the next few days reflecting these changes.

Following these build instructions: https://github.com/proteneer/timemachine#running-tests 

- [ ] Problem: jaxlib XLA extension has a GLIBC incompatibility on the system where I'm attempting to build the project. (`ImportError: /lib64/libm.so.6: version 'GLIBC_2.23' not found (required by .../envs/timemachine/lib/python3.7/site-packages/jaxlib/xla_extension.so)`)
  * Workaround: downgrade Python version, as suggested in https://github.com/tensorflow/tensorflow/issues/28660 . (Observation: This GLIBC incompatibility is encountered in a fresh python 3.7.3 environment `conda create -n timemachine`, but not in a fresh python 3.6.8 environment `conda create -n timemachine_368 python=3.6.8`)
  * Possible solution: specify compatible python versions

- [ ] Problem: cmake error encountered while executing `cmake -DBUILD_TEST=ON -DCUDA_ARCH=sm_70 ../`
    ```
    CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
    CMake 3.5 or higher is required. You are running version 2.8.12.2
    ```
  * Workaround: `pip install cmake --upgrade`
  * Possible solution: specify minimum `cmake` version in requirements.txt

- [ ] Problem: namespace errors encountered while executing `make -j4 install` : `.../timemachine/timemachine/cpp/src/nonbonded.cu(29): error: namespace "std" has no member "runtime_error"`
   * Workaround: add `#include <stdexcept>` to each of `timemachine/cpp/src/electrostatics.cu, timemachine/cpp/src/harmonic_angle.cu, timemachine/cpp/src/harmonic_bond.cu, timemachine/cpp/src/lennard_jones.cu, timemachine/cpp/src/nonbonded.cu, timemachine/cpp/src/periodic_torsion.cu, timemachine/cpp/src/restraint.cu, timemachine/cpp/src/stepper.cu`

- [ ] Problem: `ModuleNotFoundError`s when executing pytests: `timemachine.lib`, `rdkit`, `simtk` not found
  * Workaround: Append `path/to/timemachine` to `sys.path`, and `conda install -c rdkit rdkit`, `conda install -c omnia openmm`.
  * Possible solution: Add a setup.py, and add `rdkit` and `openmm` to requirements.txt

**Comment by proteneer** [comment]
> jaxlib XLA extension has a GLIBC incompatibility on the system where I'm attempting to build the project.

This is unfortunate. I do all my dev work on 3.6 since ubuntu 18.04 is pinned to it. I'm not super familiar with the Conda world. But I'm happy to specify python 3.6 somewhere though.

> CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
Many devs install cmake through their package manager (eg cmake) force installing a python-based cmake through requirements.txt may cause unexpected behavior if they forget to deactivate their venv upon exiting

> Problem: namespace errors encountered while executing make -j4 install : .../timemachine/timemachine/cpp/src/nonbonded.cu(29): error: namespace "std" has no member "runtime_error"

Sigh this seems to another case of compilers deciding to do things inconsistently. What version of gcc are you using and what OS? Would be great if I can repro this in order to make the builds more reliable. 

>  Problem: ModuleNotFoundErrors when executing pytests: timemachine.lib, rdkit, simtk not found

timemachine.lib - I usually just shove the src repo to $PYTHONPATH which isn't the best way, how do others do this?
rdkit, simtk - these two packages are pretty hard to install vanilla, and we should probably specify a version for these

**Comment by proteneer** [comment]
To add a little bit more color commentary: 

We usually run the timemachine either in "client mode" or "worker mode"

In worker mode we need CUDA and all the custom_ops in the .lib folder, but none of the stuff in RDKit/OpenMM. The workers are designed to have as minimal number of dependencies as possible and directly take in a self-contained and serialized binary data.

``` python
# worker.py
import argparse
import numpy as np
import time
import os
import logging
import pickle
from concurrent import futures
import grpc
import service_pb2
import service_pb2_grpc
from threading import Lock
from timemachine.lib import custom_ops
```

The client mode is where all the deps come in, as rdkit/openmm are needed to prep the system, parameterize the ligand, setup waters, etc. 

So I'm not sure how to structure the setup.py in a way that's consistent.

**Comment by maxentile** [comment]
Thanks Yutong!

>But I'm happy to specify python 3.6 somewhere though.

Actually, this may be specific to just some combinations of python version and jax/jaxlib versions. If I either downgrade python version (from 3.7.3 to 3.6.8) or update from the jax and jaxlib versions specified in requirements.txt (jax==0.1.61, jaxlib==0.1.41) to the most recent versions (jax==0.1.73, jaxlib==0.1.55), I don't get the GLIBC error.

>Many devs install cmake through their package manager (eg cmake) force installing a python-based cmake through requirements.txt may cause unexpected behavior if they forget to deactivate their venv upon exiting

Good point!

>Sigh this seems to another case of compilers deciding to do things inconsistently. What version of gcc are you using and what OS? Would be great if I can repro this in order to make the builds more reliable.

Ahh, good thinking!

GCC version : 4.8.5 20150623 (Red Hat 4.8.5-36)
NVCC version: 10.2.89
OS version: CentOS 7.6.1810

A brief search indicates that this behavior changed between GCC 4 and 5. Updating to a less ancient version of GCC should resolve this issue. Specifying a minimum gcc version in cmake list might also catch this.

>timemachine.lib - I usually just shove the src repo to $PYTHONPATH which isn't the best way, how do others do this?

That works — I think the preferred way is to use a [setup.py](http://setup.py) file.

>We usually run the timemachine either in "client mode" or "worker mode"
>The client mode is where all the deps come in, as rdkit/openmm are needed to prep the system, parameterize the ligand, setup waters, etc.
>So I'm not sure how to structure the [setup.py](http://setup.py/) in a way that's consistent.

Hmm, not sure either. One way might be to say the heavier packages required by "client mode" are "extra" dependencies. The [setuptools documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) describes how to specify dynamic dependencies. Could use this to specify that these heavier dependencies are only resolved when "client mode" entry points are run.

**Comment by jchodera** [comment]
BTW, we're contracting with the awesome [Quansight folks](https://www.quansight.com/python-optimization) (several of whom are conda-forge devs) to help us migrate OpenMM and friends to conda-forge. If their help could be useful here, we could extend our contract in helping come up with a better migration path for pure conda-forge installation.

**Comment by proteneer** [comment]
> Actually, this may be specific to just some combinations of python version and jax/jaxlib versions. If I either downgrade python version (from 3.7.3 to 3.6.8) or update from the jax and jaxlib versions specified in requirements.txt (jax==0.1.61, jaxlib==0.1.41) to the most recent versions (jax==0.1.73, jaxlib==0.1.55), I don't get the GLIBC error.

we pin jax==0.1.61 and jaxlib==0.1.41 due to an issue in how vjps are computed for the on-diagonal elements of the distance matrix: https://github.com/google/jax/issues/3407

I haven't had time to guard against this in every part of the calculation yet. So for now I'm pinning jax. 

> A brief search indicates that this behavior changed between GCC 4 and 5. Updating to a less ancient version of GCC should resolve this issue. Specifying a minimum gcc version in cmake list might also catch this.

Thanks I will see if I can hunt down GCC4 somewhere. We're on GCC7 on our cluster.

> Hmm, not sure either. One way might be to say the heavier packages required by "client mode" are "extra" dependencies. The setuptools documentation describes how to specify dynamic dependencies. Could use this to specify that these heavier dependencies are only resolved when "client mode" entry points are run.

Okay we should think about this a little bit longer then before deciding.

**Comment by proteneer** [comment]
@maxentile I realized that unfortunately one of our header-only CUDA dependencies (CUB) requires C++14 - which is most likely incompletely supported in GCC4 (it supports c++1y). So it looks like we will need to be gcc5 or later.

**Comment by maxentile** [comment]
I have since installed `timemachine` :)

Also, the improvements in https://github.com/proteneer/timemachine/pull/445 make installation significantly easier
