### ISSUE TITLE
Optimize Distance Calculations

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#320]
Expanding this issue a little:

One of the inefficient parts in the timemachine is how we compute distances under a periodic system. Currently, we compute the squared distances with the following method:

Let ci, cj be the (x,y,z,w) coordinates of two particles i and j. We compute wrap(ci - cj, box)^2 where wrap takes care of the periodic boundary conditions.

Let's consider the non-periodic case where ```wrap(x) = x```

```
d2ij = (xi-xj)*(xi-xj) + (yi-yj)*(yi-yj) + (zi-zj)*(zi-zj) + (wi-wj)*(wi-wj)
```

David Clark pointed out in:

https://github.com/openmm/openmm/pull/2989/files

For non-periodic systems, an optimization is to do instead to

```
d2ij = ci.ci + cj.cj - 2ci.cj
d2ij = (xi^2+yi^2+zi^2+wi^2) + (xj^2+yj^2+zj^2+wj^2) - 2 (xi*xj + yi*yj + zi*zj + wi*wj)
```
Where ```ci.ci``` and ```cj.cj``` is precomputed once in the outer loop. This results in fewer FMA operations in the intensive inner loop.

What complicates this is the wrap(x, box) function, which is implemented as:

```
x - b*floor(x/b + 0.5f) = x - b*nearbyint(x/b)
```

OpenMM does a check for a "single periodic copy" to see if all particles involved in the interaction can be translated into a single box, and if so we can resort to dclark's trick. Quite nice.

**Comment by badisa** [comment]
@proteneer I believe we can now close this thanks to https://github.com/proteneer/timemachine/commit/d0133123c8eaa05058b227a1fb8d95a04e77022e
