### ISSUE TITLE
Update benchmarking

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#337]
we should update some of the benchmarking code to include some RBFE test cases

**Comment by maxentile** [comment]
Related: we have an RBFE test case that may be duplicated in `__main__` for a couple examples and tests (in [`examples/rbfe_single.py`](https://github.com/proteneer/timemachine/blob/639b42f4c6759e791d7caae4d2d843b13f3fc745/examples/rbfe_single.py#L87-L181), [`tests/test_free_energy.py`](https://github.com/proteneer/timemachine/blob/c5af582d4fbbfad0de17b5e1079dfff4af971155/tests/test_free_energy.py#L99-L160), [`tests/test_topology.py`](https://github.com/proteneer/timemachine/blob/c5af582d4fbbfad0de17b5e1079dfff4af971155/tests/test_topology.py#L292-L334), and now possibly in [`tests/benchmark.py`](https://github.com/proteneer/timemachine/pull/339/files#diff-9e20e8961feab6eb62577559fb7465e3153dcd3a021f5c6f7b4fab2f2ac46cb4R154-R197) ).

Should we create a `testsystems` module containing this system, that can be imported in tests, benchmark scripts, and example scripts?

**Comment by proteneer** [comment]
I think it'd be wise, but lets do this in a separate PR?

**Comment by proteneer** [comment]
Benchmarking scripts have been improved to include more relevant binding free energy systems.
