### ISSUE TITLE
Make testsystems file

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#340]
Per #337 

we should find all instances where we load in the hif2a set and a pair of ligands and have them load from a common test system function.

files of interest

```
examples/rbfe_single.py
tests/test_free_energy.py
tests/test_topology.py
tests/benchmark.py
in a separate PR soon to come
tests/test_minimizer.py
```

**Comment by maxentile** [comment]
The singleton design in https://github.com/proteneer/timemachine/blob/12bcc2e8d590ea6eded7124aa316ce14a6bfc703/testsystems/relative.py has caused problems, e.g. when an application mutates the test system. Modeling this instead on the testsystems modules in openmmtools, pymbar, or msmbuilder would be a good idea.

**Comment by proteneer** [comment]
I think this is mostly done.
