### ISSUE TITLE
NPT support?

### ISSUE THREAD

**Issue by maxentile** [proteneer/timemachine#373]
@proteneer : Could you please comment on any design constraints that affect how `timemachine` could support NPT simulation?

I think earlier there were more stringent design constraints that would have ruled out methods like the `MonteCarloBarostat` used in OpenMM. Currently, however, I'm not aware of design constraints that would rule out `MonteCarloBarostat`.

There may be different sets of requirements for two tasks:
* "NPT equilibration" - get a single box volume suitable for NVT production simulation
* "NPT production" - sample box fluctuations during production simulation

**Comment by maxentile** [comment]
Following up on [a comment from the other thread](https://github.com/proteneer/timemachine/pull/372#issuecomment-801406388):
>Minimizing the energy is not the proper objective. You can imagine a single particle with a +1 charge would optimize the box into an infinitely large box in order to minimize U. You need to optimize the box into an appropriate pressure, so what you'd want really is still to compute current virial and compare it against a target virial. 

If we minimize the NPT reduced potential `u(coords, box) + p V(box)`, rather than the potential energy `U(coords, box)`, that would rule out infinitely large-volume boxes from appearing as minimizers in this example. Would the NPT reduced potential be a suitable objective to minimize for (possibly deterministic) NPT equilibration?

**Comment by maxentile** [comment]
Summarizing offline discussions:
* The priority is to solve the "NPT equilibration" task, before the "NPT production" task. A shared solution to both tasks would be preferable, if possible.
* A solution to the "NPT equilibration" task must address a possible deficiency of the Monte Carlo barostat, namely slow equilibration times.
* If needed, a solution can introduce a dependence on the virial. 

I'd imagine the default solution is to use OpenMM MC barostat. I've plotted the equilibration behavior of the OpenMM MC barostat on a TIP3P waterbox, initialized with a padded box, as we vary the proposal frequency: https://gist.github.com/maxentile/930d0686f9927d683f650c9c67cdb575

![image](https://user-images.githubusercontent.com/5759036/111790394-86a07000-8898-11eb-8a7d-e35f4fde6ccb.png)

Note that increasing the barostat proposal frequency increases the wall time per step, up to a factor of ~3x if we make 1 proposal per MD step. I think this suggests the possible "slow equilibration time" deficiency of the MC barostat can be addressed by adjusting this setting.

Switching the x axis from # MD steps to wall time, and focusing on the fastest barostat proposal frequencies:

![image](https://user-images.githubusercontent.com/5759036/111790431-90c26e80-8898-11eb-8af1-d52e57168e18.png)

Approximate take-aways:
* recovering from a box padding of around +5Å from NPT-typical range takes around a few hundred to a few thousand MD steps, if the barostat proposal frequency is high enough (> 1 proposal per ~ 10 MD steps).
* A water box can be approximately re-equilibrated in ~1 GPU second if the barostat proposal frequency is chosen appropriately.
* Reducing the barostat proposal frequency increases the apparent equilibration time ~ linearly.

Initially, I think this suggests the OpenMM barostat equilibrates fast enough for timemachine's purposes, provided that we pick the proposal frequency fast enough.

A possible solution I considered would be to apply the OpenMM barostat to timemachine systems, but this would in general produce incorrect box volumes due to differences in long-range treatment that are presumed to have a significant effect on equilibrium densities. This rules out "call OpenMM barostat", and replaces it with two options: "clone the OpenMM barostat into timemachine", or "clone timemachine long-range treatment as an OpenMM CustomNonbondedForce". Based on offline discussion, cloning the timemachine long-range treatment as an OpenMM CustomNonBondedForce is ruled out because it would trigger a requirement to clone all timemachine forces into OpenMM and keep them in sync for the lifetime of the project. That leaves "clone the OpenMM barostat into timemachine."

I've studied the OpenMM barostat implementation and think I have a good sense of how to clone it in numpy, for inclusion as a step in timemachine's `minimize_host_4d` routine. The main error-prone aspects of the new implementation will be related to how the OpenMM barostat proposal scales molecular centers. (Some additional aspects that will require care: molar unit conversions, possible ambiguity in treatment of velocities upon coordinate rescaling, and the proposal-scale adaptation.)

Before proceeding to clone the OpenMM barostat, I plan to check whether minimizing `u_npt(coords, box)` (rather than minimizing `U(coords)` with fixed box) would also be a performant solution to the "NPT equilibration" task, since it would appear to require a lower implementation and maintenance cost than cloning the OpenMM barostat. (Would require: (1) writing a function to compute `u_npt(coords, box)` in terms of `U(coords, box)`, `temperature`, `pressure`, and `volume(box)`, (2) computing `d u_npt / d box` by finite difference, (3) calling scipy optimize.)

However, relative to cloning the MC barostat, (1) this approach has an additional "scientific risk" in that we don't know if minimizing `-u_npt` would be a robust method for equilibrating the box, and (2) if successful, it would only address equilibration, but not production.

**Comment by jchodera** [comment]
@maxentile : This is awesome! Thanks for this informative post.

One quick observation: If you do implement the Monte Carlo barostat, I _highly_ recommend adding an ideal molecular gas test case and checking the average volume matches ideal gas expectations. This was an incredibly useful test case for identifying subtle bugs in all of my previous implementations.

**Comment by peastman** [comment]
If you haven't already read it, take a look at [the original paper for the algorithm](https://doi.org/10.1016/j.cplett.2003.12.039).  Figure 2b shows an analysis similar to yours.  They measured how long it takes (in simulation time) for the box to adapt to a sudden pressure change when using various proposal frequencies.  They found no significant difference between 5 and 10.  25 was slightly slower, though not too much.  Higher values did take significantly longer to adapt.

That's why I chose 25 as the default value.  It's almost as fast as a smaller value in terms of equilibration speed, and almost as fast as a larger value in terms of computation time.  But it's not quite optimal for either one.  It would be better to use a somewhat smaller value during equilibration and a somewhat larger value during production.
