### ISSUE TITLE
record FMA compiler bug

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#386]
Recording the FMA bug recently discovered here, so we can reference this issue in a patch. Thanks to @scottlegrand for identifying that the issue is because of the fma on denormed floats

``` cuda
#include <cstdio>

#define FIXED_EXPONENT             0x1000000000

void __global__ k_test(float a, float b, float c, float d, double *out) {


    float res = (a*b)+(c*d);

    unsigned long long cast = static_cast<unsigned long long>(llrint(res*FIXED_EXPONENT));

    printf("gpu a*b+c*d %llu\n", cast);

    out[0] = a+b+c+d;

}


void h_test(float a, float b, float c, float d) {

    float res = (a*b)+(c*d);

    unsigned long long cast = static_cast<unsigned long long>(llrint(res*FIXED_EXPONENT));

    printf("gpu a*b+c*d %llu\n", cast);

}


int main() {

    double *res;

    auto err = cudaMalloc(&res, sizeof(*res));#include <cstdio>

#define FIXED_EXPONENT             0x1000000000

void __global__ k_test(float a, float b, float c, float d, double *out) {


    float res = (a*b)+(c*d);

    unsigned long long cast = static_cast<unsigned long long>(llrint(res*FIXED_EXPONENT));

    printf("gpu a*b+c*d %llu\n", cast);

    out[0] = a+b+c+d;

}


void h_test(float a, float b, float c, float d) {

    float res = (a*b)+(c*d);

    unsigned long long cast = static_cast<unsigned long long>(llrint(res*FIXED_EXPONENT));

    printf("gpu a*b+c*d %llu\n", cast);

}


int main() {

    double *res;

    auto err = cudaMalloc(&res, sizeof(*res));

    // denorms
    float eps_j = 0.12814913690090179443;
    float deps_dl_i =-0.12525972723960876465;
    float eps_i = 0.12525972723960876465;
    float deps_dl_j = 0.12814913690090179443;

    k_test<<<1,1>>>(eps_j,deps_dl_i,eps_i,deps_dl_j,res);
    k_test<<<1,1>>>(eps_i,deps_dl_j,eps_j,deps_dl_i,res); // not bitwise identical

    cudaDeviceSynchronize();

    h_test(eps_j,deps_dl_i,eps_i,deps_dl_j);
    h_test(eps_i,deps_dl_j,eps_j,deps_dl_i); // not bitwise identical

    // no denorms case seems to be working fine
    // eps_j = 0.1;
    // deps_dl_i = 0.2;
    // eps_i = -0.3;
    // deps_dl_j = -0.4;

    // k_test<<<1,1>>>(eps_j,deps_dl_i,eps_i,deps_dl_j,res);
    // k_test<<<1,1>>>(eps_i,deps_dl_j,eps_j,deps_dl_i,res);


    // cudaDeviceSynchronize();


}

    // denorms
    float eps_j = 0.12814913690090179443;
    float deps_dl_i =-0.12525972723960876465;
    float eps_i = 0.12525972723960876465;
    float deps_dl_j = 0.12814913690090179443;

    k_test<<<1,1>>>(eps_j,deps_dl_i,eps_i,deps_dl_j,res);
    k_test<<<1,1>>>(eps_i,deps_dl_j,eps_j,deps_dl_i,res); // not bitwise identical

    cudaDeviceSynchronize();

    h_test(eps_j,deps_dl_i,eps_i,deps_dl_j);
    h_test(eps_i,deps_dl_j,eps_j,deps_dl_i); // not bitwise identical

    // no denorms case seems to be working fine
    // eps_j = 0.1;
    // deps_dl_i = 0.2;
    // eps_i = -0.3;
    // deps_dl_j = -0.4;

    // k_test<<<1,1>>>(eps_j,deps_dl_i,eps_i,deps_dl_j,res);
    // k_test<<<1,1>>>(eps_i,deps_dl_j,eps_j,deps_dl_i,res);


    // cudaDeviceSynchronize();


}```

**Comment by proteneer** [comment]
closing this since its mostly used for referencing.

**Comment by maxentile** [comment]
Slightly reduced this test case

```cuda
#include <cstdio>


void __global__ k_okay(float a, float b, float c, float d, double *out) {
    float ab = a * b;
    float cd = c * d;

    printf("%0.20f\n", ab+cd);

    out[0] = ab*cd; // or `ab/cd` would also suffice
}


void __global__ k_not(float a, float b, float c, float d, double *out) {
    float ab = a * b;
    float cd = c * d;

    printf("%0.20f\n", ab+cd);

    out[0] = ab-cd; // or `0` or `ab` or `cd` or `a+b+c+d` etc. here would also cause print statement above to != 0
}


int main() {
    double *res;
    auto err = cudaMalloc(&res, sizeof(*res));

    float a = 0.1;
    float b = 0.1;
    float c = 0.1;
    float d = -0.1;
    
    printf("a*b+c*d using k_okay = "); // 0.00000000000000000000
    k_okay<<<1,1>>>(a,b,c,d,res);
    cudaDeviceSynchronize();
    
    printf("a*b+c*d using k_not = "); // -0.00000000040978193061
    k_not<<<1,1>>>(a,b,c,d,res);
    cudaDeviceSynchronize();
}
```

**Comment by maxentile** [comment]
To confirm I'm following this issue properly.

Although this is expected behavior for a fused-multiply-add, this is a bug because we did not want the compiler to treat "replace `a*b + c*d` with `fma(a, b, c*d)`" as a sound transformation in our context, correct?

(The fix in https://github.com/proteneer/timemachine/pull/387 forces the compiler not to fuse these, in a context where the difference between `round(round(a*b) + round(c*d))` and `round(a*b + round(c*d))` is crucial. But we wouldn't want to set `--fmad=false` globally because we would still like to allow the compiler to use fused-multiply-adds in other contexts.)

```cuda

#include <cstdio>

int main() {
    float a = 0.1;

    float f1 = a*a - a*a;       // 0.00000000000000000000
    float f2 = fma(a, a, -a*a); // -0.00000000040978193061

    printf("f1 = %0.20f\nf2 = %0.20f\n", f1, f2);
}
```

**Comment by proteneer** [comment]
> Although this is expected behavior for a fused-multiply-add

Yes, although it was certainly unexpected on initial discovery.

> The fix in #387 forces the compiler not to fuse these

Correct

> But we wouldn't want to set --fmad=false globally because we would still like to allow the compiler to use fused-multiply-adds in other contexts.)

Correct again, disabling fmas globally would be terrible for performance.

**Comment by proteneer** [comment]
I think there's still a compiler bug, because gcc does *not* generate an FMA instruction for a*a - a*a, presumably because it wouldn't be zero. I don't think the FMA should be permitted by the compiler in instances where it would violate commutativity. Whether or not this counts as a commutative example is up for debate. It's also strange that on CUDA, bigger numbers (non-denormed floats) did not exhibit this behavior.

**Comment by scottlegrand** [comment]
So for this contrived example, you are right, but in general, I don't see
how you detect commutativity a priori. And especially for this example
where the values of a,b,c and d are fed in as input parameters. As for
bigger numbers not displaying that behavior, those numbers also came with
mostly zero mantissas, no?
    // no denorms case seems to be working fine
     eps_j = 0.1;
     deps_dl_i = 0.2;
     eps_i = -0.3;
     deps_dl_j = -0.4;

gpu a*b+c*d -0.000000000215413908932760023163
gpu a*b+c*d 0.000000000215413908932760023163
cpu a*b+c*d 0
cpu a*b+c*d 0
gpu a*b+c*d 0.140000000596046447753906250000
gpu a*b+c*d 0.140000000596046447753906250000

I see the same sort of roundoff issues if I expand the precision for the
printf

**Comment by maxentile** [comment]
Thanks for diving into this with us @scottlegrand !

>I think there's still a compiler bug, because gcc does not generate an FMA instruction for `a*a - a*a`, presumably because it wouldn't be zero.

I'm not sure this comparison is complete, as gcc also doesn't generate an `fma(a, b, c)` instruction for an input like `a*b+c` https://godbolt.org/z/zs9PEMscM (where nvcc does https://godbolt.org/z/q8d5TGcPv )

>I don't think the FMA should be permitted by the compiler in instances where it would violate commutativity. 
>in general, I don't see how you detect commutativity a priori. And especially for this example where the values of a,b,c and d are fed in as input parameters. 

I'm not sure exactly what condition we would have needed the compiler to enforce, short of essentially `fmad=false`.

One way of looking at the issue is that the compiler could equally well have generated `fma(a, b, c*d)` or `fma(c, d, a*b)` as a way to compute `a*b + c*d` (up to rounding error), and when the compiler chose one of those orders, it broke a symmetry that the bitwise-cancellation code relied on.

Is the condition we would have preferred something like, "don't generate an `fma` instruction in one order if it would also be possible to generate the instruction in the opposite order?"

If so, I guess that would rule out the compiler generating `fma(a, b, c)` instructions whenever `c` can be expressed as a product. Intuitively that seems like it would be pretty restrictive.

**Comment by proteneer** [comment]
The other interesting bit to note is that it looks like the FMA does generate identical bits for the denormalized floating points except for the sign bit at the front:

```
gpu a*b+c*d -0.000000000215413908932760023163
gpu a*b+c*d 0.000000000215413908932760023163
```

This sign bit is correct in the non-denormed case. At this point I think it's probably best for a professional compiler engineer to look into this further.
