### ISSUE TITLE
downgrade pymbar to 3.0.3

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#477]
Been running into convergence issues with our decoupling stage via pymbar:

```
WARNING: Did not converge to within specified tolerance.
max_delta = 3.999622e-03, tol = 1.000000e-12, maximum_iterations = 250, iterations completed = 
....
_computeAsymptoticCovarianceMatrix
    check_w_normalized(W, N_k)
  File "/home/localuser/miniconda3/envs/py37/lib/python3.7/site-packages/pymbar/utils.py", line 360, in check_w_normalized
    (firstbad, column_sums[firstbad], np.sum(badcolumns)))
pymbar.utils.ParameterError: Warning: Should have \sum_n W_nk = 1.  Actual column sum for state 0 was 0.917241. 63 other columns have similar problems
```

This might be related to:

https://github.com/choderalab/pymbar/issues/419

**Comment by maxentile** [comment]
@proteneer -- can you confirm that downgrading from 3.0.5 to 3.0.3 solved the issue?

Point of uncertainty: relation to numerical overflows in the `u_kn` matrix, which might be a separate issue: https://github.com/proteneer/timemachine/issues/481

**Comment by proteneer** [comment]
unrelated to pymbar in the end (and has to do with #481).
