### ISSUE TITLE
Misc estimator things to cleanup

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#486]
1) Fix gradients with endpoint correction to use the correct end states
2) Change barostat frequency from 5->25
3) Change du/dp frequency from 5->100 and measure perf differences.

**Comment by proteneer** [comment]
Current Timings for 100k steps on hif2a on master

```
x_interval=1000
du_dp_interval=5
barostat_interval=5
Multiple_steps: 89 seconds
Delta_U's time: 6.5 seconds
```

**Comment by proteneer** [comment]
branch: estimator_cleanup (using `ctxt.multiple_steps_U` as opposed to `ctxt.multiple_steps` and `delta_Us` separately)

`
x_interval=1000
du_dp_interval=5
barostat_interval=5
total time 89.58291339874268
`

(7% speedup roughly)

**Comment by maxentile** [comment]
Closed by https://github.com/proteneer/timemachine/pull/487
