### ISSUE TITLE
Summed Potential

### ISSUE THREAD

**Issue by badisa** [proteneer/timemachine#533]
### Background

A big performance bottle neck is copying data between the CPU and the GPU. Currently if we want to use the GPU potentials as a bound impl (IE as a python object we call `execute` on) we must sum the resulting values in python, resulting in N (the number of potentials) copies from the GPU to the CPU. We would like to instead combine a set of potentials into a potential that will perform the summing on the GPU and only copy data to the CPU once.

### Design Considerations

* Should function like any other potential, and be constructed from a set of other potentials.

**Comment by badisa** [comment]
One good place to use the new summed potential would be in our minimizer code: https://github.com/proteneer/timemachine/blob/master/md/minimizer.py#L63

**Comment by proteneer** [comment]
Resolved by #537
