### ISSUE TITLE
Add cudaDeviceReset to end of Tests

### ISSUE THREAD

**Issue by badisa** [proteneer/timemachine#563]
Required to detect memory leaks. 

### Tasks

- Add pybind function to call the reset from python
- Add step at the very end of pytest to reset the device

**Comment by mcwitt** [comment]
This was partly addressed in https://github.com/proteneer/timemachine/pull/542/commits/9b92c89131d6af471bf37d901107774b31a1e818 (but only in `test_nonbonded.py`).

**Comment by mcwitt** [comment]
Fixed in #569
