### ISSUE TITLE
Standardize ff references

### ISSUE THREAD

**Issue by maxentile** [proteneer/timemachine#602]
From: https://github.com/proteneer/timemachine/pull/591#pullrequestreview-870943891

>We may want to add a less obtuse way of referencing the default forcefields than open("timemachine/ff/params/...py") but that can be done in a later PR.

There are currently several ways we do this path search -- may be better to access via an import

**Comment by badisa** [comment]
@maxentile Can this be closed with this (https://github.com/proteneer/timemachine/commit/46e4c351ff0de3d47d974a6d3d9ce80c35a51552) change?

**Comment by maxentile** [comment]
Yes!
