### ISSUE TITLE
Option to freeze `d_volume_scale` in barostat?

### ISSUE THREAD

**Issue by maxentile** [proteneer/timemachine#622]
Possible problem:

The Monte Carlo barostat contains some history-dependent state, used for on-the-fly adaptation of the box-scaling proposal (see `num_attempted`, `num_accepted`, `d_volume_scale` in [production implementation](https://github.com/proteneer/timemachine/blob/61e068297ce26083b1168535ba908f9987696605/timemachine/cpp/src/barostat.cu#L246-L265). see also `n_proposed`, `acceptance_fraction`, `max_delta_volume` in [python implementation](https://github.com/proteneer/timemachine/blob/61e068297ce26083b1168535ba908f9987696605/timemachine/md/barostat/moves.py#L149-L180)).

This could potentially introduce a bias when used [as an approximate MCMC move](https://github.com/proteneer/timemachine/blob/61e068297ce26083b1168535ba908f9987696605/timemachine/md/moves.py#L72). For example, we might mistakenly assume that `xs_updated = [npt.move(x) for x in xs]` updates each of a list of states independently, but in fact `x[i]` influences which value of `d_volume_scale`, etc. will be used to update `x[i>1]`...

How much bias?
* Unknown -- would guess very small. (Initially considering this a low-priority "cleaning" item unless this starts biting us somewhere.)

-----------

Possible solutions:
* Reset `num_attempted=0`, `num_accepted=0`, `d_volume_scale=some_default` every time an NPT move is used. Possible complication: While this avoids interaction between different calls to npt.move,  each move is individually made up of more non-markovian steps (since more likely to adjust `d_volume_scale` on-the-fly during the move, since `num_accepted`, `num_attempted` counters are low and `d_volume_scale` is not pre-adapted).
* Add an `adapt_proposal_scale` boolean option to the barostat. (Set `true` to obtain a good system-dependent `d_volume_scale`, then set `false` to freeze the value of `d_volume_scale` before doing anything like ` [npt.move(x) for x in xs]`.) This can probably be emulated without touching the logic, by setting the counters `num_attempted = some_giant_number`, `num_accepted = some_giant_number / 2`, where `some_giant_number` is chosen large enough that `num_accepted / num_attempted` is guaranteed to be in the range [0.25, 0.75] during the lifetime of the move even if 0% or 100% of moves are accepted)

**Comment by jchodera** [comment]
There's another alternative here: If the self-tuning equations that adapt the perturbation to achieve good acceptance rates satisfy certain conditions, this can be a form of stochastic approximation that ensures the correct expectations are generated, and can even satisfy the CLT under certain conditions. There's a significant literature on this, but [this paper](https://projecteuclid.org/journals/annals-of-applied-probability/volume-16/issue-3/On-the-ergodicity-properties-of-some-adaptive-MCMC-algorithms/10.1214/105051606000000286.full) may be a good entry point.

**Comment by jchodera** [comment]
In fact, it seems that [this paper](https://projecteuclid.org/journals/bernoulli/volume-11/issue-5/On-adaptive-Markov-chain-Monte-Carlo-algorithms/10.3150/bj/1130077595.full) analyzes a case (and proposes an ergodic adaptation algorithm) very simpler to the exact case of interest.

**Comment by maxentile** [comment]
Thanks, John!

Will take a look at these two adaptive MCMC references. (Another on my reading list here is [Andrieu, Thoms, 2008] Tutorial on Adaptive MCMC https://people.eecs.berkeley.edu/~jordan/sail/readings/andrieu-thoms.pdf . Another heading this falls under might be "adaptive SMC.")

Expanding context a bit: Concern is not about adaptation over time of *a single chain*

```python
traj = [x0]
for _ in range(1000):
   traj.append(npt.move(traj[-1]))
```

but with unintended shared state / interactions *among chains*

```python
arbitrary_x0s = [x_bigbox, x_smallbox, x_goldibox, ...]

def apply_move_pseudo_independently(xs):
   return [npt.move(x) for x in xs]

updated_x1s = apply_move_pseudo_independently(arbitrary_x0s)

# ... do other stuff that assumes each x was updated independently of the others
# ... (e.g. compute incremental importance weights)
```

Will take a look if something like this case is analyzed in these references.

-------

Aside: it might also be something we can find a reference for under the heading "adaptation within SMC", but examples that come to mind always have a sync barrier:
* Apply kernel[t] independently to all particles at time t, update kernel params, ..., apply kernel[t+1] independently to all particles at time t+1, ...

We would instead want an analysis where the sync barrier is omitted:
* apply kernel[t][0] to one particle, update kernel params, apply kernel[t][1] to next particle, update kernel params, ...
