### ISSUE TITLE
IndexError when molecule contains no improper torsions

### ISSUE THREAD

**Issue by maxentile** [proteneer/timemachine#623]
Parameterization assumes non-empty list of matches here.

Detailed error message:

<details>

```
File "/home/jfass/Documents/GitHub/timemachine/timemachine/fe/free_energy.py", line 119, in prepare_host_edge
    final_params, final_potentials = self._get_system_params_and_potentials(ff_params, hgt)
  File "/home/jfass/Documents/GitHub/timemachine/timemachine/fe/free_energy.py", line 42, in _get_system_params_and_potentials
    combined_params, combined_potential = fn(*params)
  File "/home/jfass/Documents/GitHub/timemachine/timemachine/fe/topology.py", line 196, in parameterize_periodic_torsion
    proper_params, improper_params
  File "/home/jfass/Documents/GitHub/timemachine/timemachine/fe/topology.py", line 322, in parameterize_periodic_torsion
    improper_params, improper_potential = self.parameterize_improper_torsion(improper_params)
  File "/home/jfass/Documents/GitHub/timemachine/timemachine/fe/topology.py", line 314, in parameterize_improper_torsion
    params, idxs = self.ff.it_handle.partial_parameterize(ff_params, self.mol)
  File "/home/jfass/Documents/GitHub/timemachine/timemachine/ff/handlers/bonded.py", line 174, in partial_parameterize
    return self.static_parameterize(params, self.smirks, mol)
  File "/home/jfass/Documents/GitHub/timemachine/timemachine/ff/handlers/bonded.py", line 216, in static_parameterize
    return params[param_idxs], np.array(improper_idxs, dtype=np.int32)
IndexError: arrays used as indices must be of integer (or boolean) type
```

</details>

------------

To reproduce:
```python
from timemachine.md import enhanced

ff = ... # e.g. openff 1.1.0 + am1ccc
mol = ... # something that won't be assigned impropers by chosen ff, e.g. mobley_1019269 in FreeSolv

_ = enhanced.get_solvent_phase_system(mol, ff) # error
```

-----------

Possible solutions:
* Add guard for empty `improper_params` in `HostGuestTopology::parameterize_periodic_torsion`
* Add guard for empty `improper_params` in `BaseTopology::parameterize_periodic_torsion`
* Add guard after `param_idxs` are computed from `mol` and `smirks` in `ImproperTorsionHandler::static_parameterize(params, smirks, mol)`, before `params[param_idxs]` is returned
   * Possible extension: Add analogous guards for other `static_parameterize` functions that could in principle involve an empty list of matched indices
   * Possible extension: Refactor `static_parameterize` into a composition of simpler functions (similar to https://github.com/proteneer/timemachine/pull/571 )

**Comment by proteneer** [comment]
I think its best to just take care of this directly in static_parameterize. The guard can be as simple as:

```
import numpy as np

idxs = []
idxs = np.array(idxs, dtype=np.int32).reshape((-1, 4))
```

This will result in idxs with shape (0, 4)

**Comment by maxentile** [comment]
Thanks! I think `static_parameterize` is the best place for the fix. (Will add one for proper torsions as well while fresh in mind.)

>np.array([], dtype=np.int32).reshape((-1, 4))

Nice -- I didn't know about that way to do it via reshape.

(Another way I'd prefer slightly for explicitness is `np.zeros(shape=(0, 4), dtype=np.int32)`. Another way to clone the dtype, other dimensions from a reference array is `x[[False] * len(x)]`, but this is kind of cryptic...)
