### ISSUE TITLE
Modify some uses of jax numpy -> original numpy

### ISSUE THREAD

**Issue by maxentile** [proteneer/timemachine#717]
Esp. for index arrays -- see examples identified by @proteneer  in https://github.com/proteneer/timemachine/pull/716#discussion_r847727443

**Comment by maxentile** [comment]
A large fraction of these are index arrays -- may want to standardize to always use original numpy for integer arrays (also potentially in files that didn't appear in the diff accompanying #716 )

**Comment by maxentile** [comment]
I've started categorizing the list of 40 requested changes to clarify intent, with the aim of applying this intent across other files / lines that do not appear in the diff accompanying #716 :

Location:
* tests (33/40)
    * 27/40 in test_reweighting.py
    * 6/40 in test_jax_utils.py
    * 2/40 in test_jax_nonbonded.py
* attic (3/40)
    * 3/40 in attic'd potentials (2 in evp.py, 1 in shape.py)
* timemachine (3/40)
    * 2/40 in fe/reweighting.py
    * 1/40 in optimize/protocol.py
    * 1/40 in potentials/nonbonded.py

-------

Usage type:
* integer index arrays:
    * jnp.triu_indices
    * jnp.*, dtype=int
    * jnp.arange
    * N_k = jnp.array
* reshaping inside of Jax JIT functions: jnp.newaxis
* float array construction: jnp.linspace, jnp.ones, jnp.zeros, jnp.diag, jnp.eye
* int math: jnp.sum( int_array )
* float math: jnp.sum, jnp.mean, jnp.trapz, jnp.exp, jnp.matmul
* array concatenation: jnp.vstack, jnp.array, jnp.stack
* assertions: jnp.isfinite, jnp.isclose
* constants: jnp.inf
* printing: jnp.set_print_options

--------

@proteneer: Could you comment briefly on the general motivation for these changes?

The motivation for integer index arrays is the only one that's currently transparent to me. (Since it can cause errors with slicing.) In other cases, I've defaulted / preferred to use the jax numpy versions and not noticed a drawback yet.

**Comment by proteneer** [comment]
Safety and Consistency:

Safety: By default I'd prefer numpy over jax.numpy, since jax arrays aren't as strict as numpy arrays when it comes to `dtype`, i.e. declaring a `jax.ndarray(..., dtype=np.float64)` may not actually be 64bit unless the correct XLA flags are turned on. This may make tests comparing against jax arrays to have weird behavior.

Consistency: many of them are located in areas where the lines directly above or below were written in numpy. Personally I prefer to use vanilla numpy and use jax numpy only when I care about vmap/jit/grad types of things.

**Comment by maxentile** [comment]
Thanks! I think that clears up motivation several of the remaining cases: (1) construction of non-integer arrays with specified dtype, and (2) some instances of performing math on numpy arrays.

(Lower urgency, but still unclear: Preferences on (1) assertions (prefer np.isfinite over jnp.isfinite), (2) constants (prefer np.inf over jnp.inf), (3) reshaping (prefer np.newaxis over jnp.newaxis).)
