### ISSUE TITLE
Check chiral consistency at the end-states

### ISSUE THREAD

**Issue by proteneer** [proteneer/timemachine#773]
Introduction of chiral restraints implies that we should probably (on the first pass) check and flag when a chiral inversion is explicitly defined.

**Comment by maxentile** [comment]
Mostly addressed by https://github.com/proteneer/timemachine/pull/908 https://github.com/proteneer/timemachine/pull/919 https://github.com/proteneer/timemachine/pull/1230 https://github.com/proteneer/timemachine/pull/1243 https://github.com/proteneer/timemachine/pull/1255 https://github.com/proteneer/timemachine/pull/1256 https://github.com/proteneer/timemachine/pull/1315 ...
